on: push

name: lint
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: npm install
      - run: npm run lint
